--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

-- Started on 2024-06-13 12:06:57

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 5 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 4795 (class 0 OID 0)
-- Dependencies: 5
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 16408)
-- Name: Posts; Type: TABLE; Schema: public; Owner: tcit-api
--

CREATE TABLE public."Posts" (
    "Id" bigint NOT NULL,
    "Nombre" text NOT NULL,
    "Descripcion" text NOT NULL
);


ALTER TABLE public."Posts" OWNER TO "tcit-api";

--
-- TOC entry 216 (class 1259 OID 16407)
-- Name: Posts_Id_seq; Type: SEQUENCE; Schema: public; Owner: tcit-api
--

ALTER TABLE public."Posts" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Posts_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 16402)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: tcit-api
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO "tcit-api";

--
-- TOC entry 4789 (class 0 OID 16408)
-- Dependencies: 217
-- Data for Name: Posts; Type: TABLE DATA; Schema: public; Owner: tcit-api
--

COPY public."Posts" ("Id", "Nombre", "Descripcion") FROM stdin;
1718286772508	Post 4	Fourth app post
1718292000910	Post 1	First app post
1718292007422	Post 2	Second app post
\.


--
-- TOC entry 4787 (class 0 OID 16402)
-- Dependencies: 215
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: tcit-api
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20240613123136_InitialMigration	8.0.6
\.


--
-- TOC entry 4797 (class 0 OID 0)
-- Dependencies: 216
-- Name: Posts_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: tcit-api
--

SELECT pg_catalog.setval('public."Posts_Id_seq"', 1, true);


--
-- TOC entry 4643 (class 2606 OID 16414)
-- Name: Posts PK_Posts; Type: CONSTRAINT; Schema: public; Owner: tcit-api
--

ALTER TABLE ONLY public."Posts"
    ADD CONSTRAINT "PK_Posts" PRIMARY KEY ("Id");


--
-- TOC entry 4641 (class 2606 OID 16406)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: tcit-api
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 4796 (class 0 OID 0)
-- Dependencies: 5
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT ALL ON SCHEMA public TO "tcit-api";


--
-- TOC entry 2043 (class 826 OID 16401)
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO "tcit-api";


--
-- TOC entry 2042 (class 826 OID 16400)
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT,INSERT,DELETE,UPDATE ON TABLES TO "tcit-api";


-- Completed on 2024-06-13 12:06:57

--
-- PostgreSQL database dump complete
--

